import * as definitions from './definitions';

export const TYPES = {
  [definitions.NORMAL]: definitions.NORMAL,
  [definitions.FIRE]: definitions.FIRE,
  [definitions.WATER]: definitions.WATER,
  [definitions.ELECTRIC]: definitions.ELECTRIC,
  [definitions.GRASS]: definitions.GRASS,
  [definitions.ICE]: definitions.ICE,
  [definitions.FIGHTING]: definitions.FIGHTING,
  [definitions.POISON]: definitions.POISON,
  [definitions.GROUND]: definitions.GROUND,
  [definitions.FLYING]: definitions.FLYING,
  [definitions.PSYCHIC]: definitions.PSYCHIC,
  [definitions.BUG]: definitions.BUG,
  [definitions.ROCK]: definitions.ROCK,
  [definitions.GHOST]: definitions.GHOST,
  [definitions.DRAGON]: definitions.DRAGON,
  [definitions.DARK]: definitions.DARK,
  [definitions.STEEL]: definitions.STEEL,
  [definitions.FAIRY]: definitions.FAIRY
};

export const IMMUNITY = {
  [definitions.NORMAL]: [],
  [definitions.FIRE]: [],
  [definitions.WATER]: [],
  [definitions.ELECTRIC]: [],
  [definitions.GRASS]: [],
  [definitions.ICE]: [],
  [definitions.FIGHTING]: [],
  [definitions.POISON]: [],
  [definitions.GROUND]: [],
  [definitions.FLYING]: [],
  [definitions.PSYCHIC]: [],
  [definitions.BUG]: [],
  [definitions.ROCK]: [],
  [definitions.GHOST]: [],
  [definitions.DRAGON]: [],
  [definitions.DARK]: [],
  [definitions.STEEL]: [],
  [definitions.FAIRY]: []
};
export const WEAKNESS = {
  [definitions.NORMAL]: [],
  [definitions.FIRE]: [],
  [definitions.WATER]: [],
  [definitions.ELECTRIC]: [],
  [definitions.GRASS]: [],
  [definitions.ICE]: [],
  [definitions.FIGHTING]: [],
  [definitions.POISON]: [],
  [definitions.GROUND]: [],
  [definitions.FLYING]: [],
  [definitions.PSYCHIC]: [],
  [definitions.BUG]: [],
  [definitions.ROCK]: [],
  [definitions.GHOST]: [],
  [definitions.DRAGON]: [],
  [definitions.DARK]: [],
  [definitions.STEEL]: [],
  [definitions.FAIRY]: []
};
export const STRENGTH = {
  [definitions.NORMAL]: [],
  [definitions.FIRE]: [],
  [definitions.WATER]: [],
  [definitions.ELECTRIC]: [],
  [definitions.GRASS]: [],
  [definitions.ICE]: [],
  [definitions.FIGHTING]: [],
  [definitions.POISON]: [],
  [definitions.GROUND]: [],
  [definitions.FLYING]: [],
  [definitions.PSYCHIC]: [],
  [definitions.BUG]: [],
  [definitions.ROCK]: [],
  [definitions.GHOST]: [],
  [definitions.DRAGON]: [],
  [definitions.DARK]: [],
  [definitions.STEEL]: [],
  [definitions.FAIRY]: []
};
